language: python
python:
- 3.3
- 3.4
- 3.5
install:
- xargs -L 1 pip install < requirements.txt
- pip install -r requirements-tests.txt
script: py.test --cov=morinkit --pep8 tests
after_success: codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: morinlab
  password:
    secure: O2xM9EFnEvf+lU6QFAKHSi9i/xXsTOX+UDYbrk8nTzKR6XvU2HbhSHHWEUOcH+XqjmkT736OzNASCEVp0xByzOF8Y5/4nTj1G6Fj5/EDzpi+KwYcOzErM/IfFgHWenmbwfVigdRsC7BxObVAAcfjyfogczTYU7iw9YbCFpx8Gy2RTGL80YuZyqmMkcEZl4xaOHSQQxaXRy0PHpMXS7RMWSWfA4IRZkkqn0Hv7Vn64nQ+tbLJaxl/fU+C+73THukkodsxf8F9FyjHTgM+5dWnpZRPyiW6Bx2UFF0IoICJxu1r8P4AB8pnjBvN4QSlEnpwVJzmwctJDkB5nJrsp2z4MTFQbHuPA8c0/3C+HNS9N0cAjneaB8GF78zaEjoZj6nstd9McsPyrvuHg+nOU3vuFUJAo+Aa6vEMmWldISs5/f9E6m6Vb1AeAGel6HziiYzP2c+Rhe05UPoYSo8eE95LVmepvoP3smij0aAKd3lFV+KQ2mJHhK58+kDP4I4VhwQkPcG4BE8NbcoYOwV0iLZrzVyI/y4tBEzz5tRMbijzTlLVMwFBi0+NQohjwATRGTCfud1bZPEof5tHZPRjWH2XlDRtmsq5Tn4FaxNv5dJzgLU7RKWd+CIrQiUPOy5tdkp2ne3+73WEOkcNbZtzw0tpBgBhhIkULFrIpLapOdgE08k=
  on:
    tags: true
    repo: morinlab/morinkit
    branch: master
  distributions: sdist bdist_wheel
